### PR TITLE
Simplest solution to exceptions in threads.

### PR DESCRIPTION
**Pull request by alanpeabody**
Just raise up into parent process, gracefully stop siblings, and
re-raise.

### CODE REVIEW

**Comment by alanpeabody** [comment]
@jayzes I have not yet verified this is doing what we want, but it was definitly the minimum effort to achieve the results desired. We can trying this out or I can move to a celluloid actor/supervisor model.

**Comment by jayzes** [comment]
@alanpeabody looks good to me - what are your thoughts?

**Review by jayzes — APPROVED** [review]

**Comment by alanpeabody** [comment]
@jayzes I am liable to just say lets go with this for now. If we have issues beyond this we can reconsider, but this lets us be flexible in our implementations as well. I will test this out in an app tomorrow.

**Comment by jayzes** [comment]
👍

**Pull request merged**
